# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Umut Işık
description: principle developer, software development, open source, Linux, PHP
logo: assets/img/logo_darkblue.png
email: umutphp@gmail.com
home_page_title: Hi, my name is Umut Işık.
home_page_text: I am a principle developer and currently working as a delivery manager at Sony. 
home_page_description: >- # this means to ignore newlines until "baseurl:"
  I spent 18 years pursuing a career on software development including e-commerce sites, content management systems, product information management systems, news portals, dating sites, learning management systems and corporate multi-layer web applications.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://umutphp.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
twitter:
  username: umutphp
  card: summary
github_username:  umutphp
linkedin_url: https://www.linkedin.com/in/isikumut/

# Build settings
markdown: kramdown
theme: minima
plugins:
  - theme: jekyll-theme-minimal

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
