# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Umut Işık
description: software development, open source, Linux, PHP, CI
logo: assets/img/logo_darkblue.png
profile_logo: assets/img/profile_logo.jpeg
email: umutphp@gmail.com
google_analytics: UA-134229259-1
home_page_title: Hi, my name is Umut Işık.
home_page_text: I am a software engineer and currently working as a delivery manager at Sony. 
home_page_description: >- # this means to ignore newlines until "baseurl:"
   I am a software engineer and I spent 18 years pursuing a career in softwares developmentincluding e-commerce sites, content management systems, product information managementsystems, translation process/memory management systems, news portals, dating sites, learningmanagement systems and corporate multi-layer web applications.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://umuts.info" # the base hostname & protocol for your site, e.g. http://example.com
twitter:
  username: umutphp
  card: summary
github_username:  umutphp
linkedin_url: https://www.linkedin.com/in/isikumut/
landing:
  sections:
    - id: experience
      title: Experience
      layout: table
      contents:
        - description: "Nov 2018 - Present, at Sony"
          title: "Delivery Manager"
          url: https://www.linkedin.com/in/isikumut/
        - description: "Apr 2016 – Nov 2018, at Sony"
          title: "PHP Sub-Competency Lead"
          url: https://www.linkedin.com/in/isikumut/
        - description: "May 2012 – Apr 2016, at Sony"
          title: "Technical Architect"
          url: https://www.linkedin.com/in/isikumut/
        - description: "Jun 2007 – May 2012, at Sony"
          title: "Senior PHP Developer"
          url: https://www.linkedin.com/in/isikumut/
        - description: Apr 2006 - May 2007, at Magnetdigital
          title: Senior PHP Developer
          url: https://www.linkedin.com/in/isikumut/
        - description: ""
          title: "Military Service"
          url: https://www.tsk.tr/
        - description: "Jan 2002 - Oct 2004, at Forsnet"
          title: "Junior PHP Developer"
          url: https://www.linkedin.com/in/isikumut/
    - id: articles
      title: Articles
      layout: list
      contents:
        - title: Escape From Local Maxima
          description: An article about changing and managing personal skills.
          url: https://www.linkedin.com/pulse/escape-from-local-maxima-umut-i%C5%9Fik/
          date: Oct 9, 2019
        - title: Adapting New Joiners To The Team
          description: In this article, I'll try to explain the focus areas (six firsts) that I always consider while creating the plan for adapting the new joiners to the teams.
          url: https://www.linkedin.com/pulse/adapting-new-joiners-team-umut-i%C5%9Fik/
          date: May 16, 2019
        - title: A Talk About Mentorship
          description: This a very subjective talk about mentorship which is generally considered as a part of in-company training.
          url: https://www.linkedin.com/pulse/talk-mentorship-umut-i%C5%9Fik/
          date: October 17, 2018
        - title: Setting Up a CI For Your Project
          description: In this article, I will share my recent experience in creating a CI pipeline from scratch for a web application managed by a medium sized development team.
          url: https://www.linkedin.com/pulse/setting-up-ci-your-project-umut-i%C5%9Fik/
          date: September 9, 2018
        - title: Infinite Loop Of Learning
          description: We are in an infinite loop of evolution; technologies, people, requirements, concepts and everything that structures the software industry evolves.
          url: https://www.linkedin.com/pulse/infinite-loop-learning-umut-i%C5%9Fik/
          date: June 1, 2017
        - title: Peaceful Workplace
          description: According to my personal work experience, I can say that those corporate weapons have temporary affect unless the team feels the ultimate peace in the workplace. 
          url: https://www.linkedin.com/pulse/peaceful-workplace-umut-i%C5%9Fik/
          date: April 9, 2017
        - title: Working At Westeros
          description: I tried to imagine how the noble houses would be if we work at Westeros.
          url: https://www.linkedin.com/pulse/working-westeros-umut-i%C5%9Fik/
          date: February 9, 2015
        - title: Self Learning Teams
          description: We should be agile in learning as we are already agile in development.
          url: https://www.linkedin.com/pulse/self-learning-teams-umut-i%C5%9Fik/
          date: January 26, 2015
        - title: Code Kata Sessions For Developers
          description: Kata is basically about repeating the techniques of an art or study in a disciplined way. 
          url: https://www.linkedin.com/pulse/code-kata-sessions-developers-umut-i%C5%9Fik/
          date: January 19, 2015
    - id: translations
      title: Translations
      layout: list
      contents:
        - title: Open Source Guides by Github
          description: Open Source Guides are a collection of resources for individuals, communities, and companies who want to learn how to run and contribute to an open source project.
          url: https://opensource.guide/tr/
        - title: Hacker Laws
          description: Laws, Theories, Principles and Patterns that developers will find useful.
          url: https://github.com/umutphp/hacker-laws-tr
        - title: The Little Go Book
          description: The Little Go Book is a free book introducing Go by Karl Seguin. I have translated it into Turkish.
          url: https://github.com/umutphp/the-little-go-book
        - title: PHP - Galat-ı Meşhur (PHP The Wrong Way)
          description: Turkish translation of the website <a href="http://www.phpthewrongway.com/" target="_blank">http://www.phpthewrongway.com/</a> which has been created in an attempt to present a pragmatic view on PHP programming. A view dictated by experience and practical consequence rather than popular trends, theory, or academic dogma.
          url: http://www.phpthewrongway.com/tr/
        - title: "PHP: Usulüne Uygun"
          description: "Turkish translation of <a href='https://www.phptherightway.com' target='_blank'>PHP: The Right Way</a> which is an easy-to-read, quick reference for PHP best practices, accepted coding standards, and links to authoritative tutorials around the Web. The translation project is owned by <a href='https://kulekci.net/' target='_blank'>Haydar Külekçi</a> and I am an humble contributor."
          url: https://kulekci.net/php-the-right-way
        - title: "Contributor Covenant Translations"
          description: "The Turkish translation of the most popular code of conduct for open source projects with over 100,000 adoptions."
          url: https://www.contributor-covenant.org/translations/
        - title: "Open source promotion cheat sheet"
          description: "This cheat sheet summarizes important steps you should follow to promote your open source project in the best conditions."
          url: https://github.com/zenika-open-source/promote-open-source-project/blob/master/README-tr.md
        - title: PHP Güvenlik El Kitabı (Deprecated)
          description: Founded in January 2005, <a href="http://phpsec.org/" target="_blank">the PHP Security Consortium (PHPSC)</a> is an international group of PHP experts dedicated to promoting secure programming practices within the PHP community. But It is not active for years.
          url: https://phpguvenlik.wordpress.com/
        - title: Code Optimization Methods
          description: Turkish translation of Code Optimization Methods repository by <a href="https://github.com/foo123" target="_blank">Nikos M.</a>
          url: https://github.com/foo123/code-optimization-methods#translations
        - title: Backend Best Practices
          description: Turkish translation of document which is a collection of general best practices for backend development by <a href="https://github.com/futurice" target="_blank">Futurice</a>.
          url: https://github.com/umutphp/backend-best-practices
        - title: API Security Checklist
          description: Turkish translation of document which is a checklist of the most important security countermeasures when designing, testing, and releasing your API.
          url: https://github.com/shieldfy/API-Security-Checklist/blob/master/README-tr.md
        - title: Clean Code For Javascript
          url: https://github.com/umutphp/clean-code-javascript-tr
          description: Turkish translation of document containing Clean Code concepts adapted for JavaScript
        - title: HTML Best Practices
          url: https://github.com/hail2u/html-best-practices/blob/master/README.tr.md
          description: Turkish translation of document containing guides for writing maintainable and scalable HTML documents
    - id: community-contributions
      title: Community Contributions
      layout: list
      contents:
        - title: CI For PHP Projects
          description: A talk about setting up CI in PHP projects. 
          url: https://kommunity.com/istanbulphp/events/php-projelerinde-ci-uygulama
          date: December 27, 2019
        - title: How to Contribute to Open Source At Kocaeli University
          description: How can we contribute to open source with its social and technical aspects? 
          url: http://bilisim.kocaeli.edu.tr/etkinlikler.php
          date: December 10, 2019
        - title: Global Day of Coderetreat (GDCR19) Facilitator
          description: Coderetreats are run by volunteers who want to help out their local developer community. 
          url: https://www.coderetreat.org/
          date: November 16, 2019
        - title: How to Contribute to Open Source
          description: How can we contribute to open source with its social and technical aspects?
          url: https://kommunity.com/software-craftsmanship-turkey/events/sosyal-ve-teknik-yonleri-ile-acik-kaynaga-nasil-katki-yapabiliriz
          date: November 6, 2019
        - title: Kadın Yazılımcı Destekleme Programı as Facilitator
          description: The main objective of the program is to create new and effective opportunities for female software developers in the male-dominated software industry and to help them to find a place among the exemplary developers in the industry.
          url: https://github.com/scturkey/WSCEP
          date: April 6, 2019
        - title: Continuous Integration
          description: I have performed a session about continuous integration and shared my experience with the audience.
          url: https://www.meetup.com/Software-Craftsmanship-Turkey/events/253854621/
          date: December 26, 2018
        - title: Global Day of Coderetreat (GDCR14) Facilitator
          description: Coderetreats are run by volunteers who want to help out their local developer community. 
          url: https://www.coderetreat.org/
          date: October 12, 2014
        - title: Global Day of Coderetreat (GDCR17) Facilitator
          description: Coderetreat is a volunteer-based, globally coordinated effort to improve software developer's skills.
          url: https://www.coderetreat.org/
          date: November 18, 2017
        - title: Functional Programming In PHP
          description: The talk is about functional programming basics and implementations of this basics on PHP.
          url: https://www.meetup.com/IstanbulPHP/events/225433639/
          date: November 21, 2015
        - title: Introduction To Web Development With PHP
          description: <a href="https://ab.org.tr/" target="_blank">Akademik Bilişim</a> <a href="https://ab.org.tr/ab11/" target="_blank">AB2011</a> İnönü University, Malatya
          url: https://ab.org.tr/ab11/ozet/32.html
          date: February 2 to 4, 2011
        - title: Introduction To PHP
          description: Introduction to Web Development With PHP within the organization of <a href="http://inetd.org.tr/" target="_blank">INETD</a>
          url: http://inetd.org.tr/
        - title: PHP And PEAR
          description: The seminar was about what is and what provided by the PEAR library in IBM Linux Center.
        - title: PHP And PEAR
          description: The seminar is held within the organisation of [Turkish Linux Users Association](LKD http://www.lkd.org.tr/).

# Build settings
markdown: kramdown
theme: minima
plugins:
  - theme: jekyll-theme-minimal

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
